# Generated by Django 4.0.4 on 2022-06-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='age_group',
            field=models.CharField(blank=True, choices=[('10-15', '10-15'), ('16-20', '16-20'), ('21-25', '21-25'), ('26-30', '26-30')], max_length=100, null=True),
        ),
    ]
