# Generated by Django 4.0.4 on 2022-06-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_program_image_alter_program_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
